#!/usr/bin/env python3
"""Generate builtin_protos.h — embed all .posa files as C string literals."""
import os, sys

def c_escape(text):
    out = []
    for ch in text:
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n')
        elif ch == '\r': out.append('\\r')
        elif ch == '\t': out.append('\\t')
        elif ord(ch) < 0x20: out.append(f'\\x{ord(ch):02x}')
        else: out.append(ch)
    return ''.join(out)

posa_dir = sys.argv[1]
out_path = sys.argv[2]

files = sorted(f for f in os.listdir(posa_dir) if f.endswith('.posa'))

with open(out_path, 'w') as out:
    out.write('/* Auto-generated by embed_protos.py — do not edit. */\n')
    out.write('#ifndef BUILTIN_PROTOS_H\n#define BUILTIN_PROTOS_H\n\n')
    out.write('static const char * const g_builtin_posa_protos[] = {\n')
    for fn in files:
        content = open(os.path.join(posa_dir, fn)).read()
        out.write(f'    /* {fn} */\n')
        out.write(f'    "{c_escape(content)}",\n')
    out.write('    NULL\n};\n\n')
    out.write('#endif /* BUILTIN_PROTOS_H */\n')

print(f"Embedded {len(files)} .posa protocol definitions into {out_path}")
